[unit-tests] Fix unit tests on Python 3.12
Error output on Python <= 3.11:
```
error: argument --node-type: invalid choice: 'invalid' (choose from 'HeadNode', 'ComputeNode', 'LoginNode')
```

Error output on Python 3.12:
```
error: argument --node-type: invalid choice: 'invalid' (choose from HeadNode, ComputeNode, LoginNode
```

Therefore, this commit uses regex to add more flexibility to the tests

Signed-off-by: Hanwen <hanwenli@amazon.com>